### ISSUE TITLE
More vignettes

### ISSUE THREAD

**Issue by nanxstats** [road2stat/liftr#10]
Like: https://github.com/yihui/knitr/tree/master/vignettes

**Comment by Spica99** [comment]
@road2stat That is great! Keep learning from the first-rate packages. :+1:  A summary list might be helpful (keep them together). You might also need index, flowchart or cheatsheet and etc. when your package growers bigger. :smiley:

**Comment by nanxstats** [comment]
@Spica99 Great advice! :+1:  Such supplementary materials for the package will be very valuable to the people who want to learn it.

**Comment by nanxstats** [comment]
Solved by adding two vignettes: `liftr-tidyverse` and `liftr-addins`.
