### ISSUE TITLE
Support running multiple Rabix workflows in single Rmd

### ISSUE THREAD

**Issue by nanxstats** [road2stat/liftr#11]
A whole project organised by single Rmd, which need redesign of header parsing and executing process.

Or separate markdowns, single Rmd single Rabix?

Feedback from NCI.

**Comment by tengfei** [comment]
This feature is important for multi-omics project documentation and report with multiple flow running.

**Comment by nanxstats** [comment]
Rabix has changed a lot since two year ago. Plus, liftr now supports including any custom Dockerfile snippets, which may help solve this issue.

For organizing R Markdown - centric projects, I also think new packages like bookdown or workflowr are offering more systematic solutions.

Closing for now.
