### ISSUE TITLE
Contribute links broken when accessed by liftr.me

### ISSUE THREAD

**Issue by batpigandme** [road2stat/liftr#24]
The links to [Contributing Guidelines](https://liftr.me/CONTRIBUTING.md), and [Contributor Code of Conduct](https://liftr.me/CONDUCT.md) from https://liftr.me/ don't work. It looks like there's a [pkgdown issue](https://github.com/hadley/pkgdown/issues/381) re. the indeterminate status of these files at the moment, as far as `pkgdown` goes. But, just wanted to point them out in the meantime. 👍

**Comment by nanxstats** [comment]
-good catch! Thanks Mara. 👍  I've switched from relative to absolute URLs for now: https://github.com/road2stat/liftr/commit/46827174e646a81a0ce7af53e1330cbcec857373 and hopefully, this could be soon fixed in pkgdown as you mentioned.
