### ISSUE TITLE
Error running Containerize addin in Rstudio

### ISSUE THREAD

**Issue by babycamel** [road2stat/liftr#37]
I'm getting the following error when I run containerize on a single file Shiny app:

Error in (header_pos[1L] + 1L):(header_pos[2L] - 1L): NA/NaN argument.

The app runs fine and has already gone live, so this appears to be a problem with lift.

**Comment by nanxstats** [comment]
@babycamel - please notice that liftr is designed for containerizing R Markdown documents, not Shiny apps.
