### ISSUE TITLE
liftr with LaTeX and .Rnw filetypes

### ISSUE THREAD

**Issue by josephsdavid** [road2stat/liftr#43]
Hello, I am working on creating a framework for reproducible research using knitr+LaTeX on .Rnw files (the ability to embed any programming language into a single source document is amazing), and was wondering if there is any implementation for that with liftr, or if I could create a pull request and start working on that.

**Comment by nanxstats** [comment]
Hello @josephsdavid  -hmm, interesting idea that made me think. This might sound personal, and no offense... but I do believe the R Markdown format can completely replace the Rnw format in 2018. Here's my reasoning:

- For the easy cases (no heavy pdf appearance customization), R Markdown does everything that Rnw can do in a simpler, more human-friendly way.
- For the advanced cases, we can customize the (PDF output) appearance of an R Markdown document freely by [using custom LaTeX templates](https://bookdown.org/yihui/rmarkdown/pdf-document.html#advanced-customization-1).

Thus I cannot really see any added value by supporting the Rnw format here in liftr, and everyone should just use R Markdown whenever possible.

**Comment by josephsdavid** [comment]
Ah I didn’t know about the custom LaTeX templates! That’s huge, thank you! Going to just do that instead

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nanxstats** [comment]
-yes! It's a pretty powerful customization mechanism and also helps separating the content (Rmd) and style (TeX) better. 👍

**Comment by josephsdavid** [comment]
Yep that was sort of the goal with LaTeX, but I still find styling my document still taking over, thank you very much!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
