### ISSUE TITLE
Error: With R version 3.5 or greater, install Bioconductor packages using BiocManager

### ISSUE THREAD

**Issue by lubianat** [road2stat/liftr#45]
Hey,

BioConductor has updated its way of installing packages, which caused an incompatibility problem with current liftr version.

The command '/bin/sh -c Rscript -e "source('http://bioconductor.org/biocLite.R');biocLite(c('FCBF/1.2.2'))"' returned a non-zero code: 1"

The issue is at : https://github.com/nanxstats/liftr/blob/4271ec88c36c57049b2ce93461cff92c412146aa/inst/templates/pkg-bioc.Rmd

I will try to work on a solution and send a pr. 

Best,
Tiago

**Comment by nanxstats** [comment]
Fixed by https://github.com/nanxstats/liftr/pull/46
