### ISSUE TITLE
Support Bioconductor Workflows

### ISSUE THREAD

**Issue by nanxstats** [road2stat/liftr#7]
It would be meaningful to support [Bioconductor Workflows](http://www.bioconductor.org/help/workflows/) for `liftr`.

Probably more flexibility for the package design is needed when we do this.

**Comment by Spica99** [comment]
It is fantastic to add `liftr` in the [workflows](http://www.bioconductor.org/help/workflows/). Will it support  _basic_ or _advaced_?

**Comment by nanxstats** [comment]
@Spica99 Both basic and advanced will be supported, of course! :smiley:

**Comment by nanxstats** [comment]
Fixed by: https://github.com/road2stat/liftr/commit/0025a006aefc0fbde1bb1fa97999146470ca3657
